# Data Insert and Cleaning

In [4]:
import pandas as pd

In [5]:
file_path = r"D:\OneDrive\Desktop\Eda project\project_data\online_retail_II.xlsx"

df_2009 = pd.read_excel(file_path, sheet_name="Year 2009-2010")
df_2010 = pd.read_excel(file_path, sheet_name="Year 2010-2011")

concated_data = pd.concat([df_2009, df_2010], ignore_index=True)

data = pd.DataFrame(concated_data)
print("Data Frame Created Successfully")
print(f"shape of the data: {data.shape}")

Data Frame Created Successfully
shape of the data: (1067371, 8)

### Removing Duplicates

In [6]:
duplicate_rows = data.duplicated().sum()
if duplicate_rows == 0:
    print("No Duplicates Found")
else :
    data.drop_duplicates(inplace=True) 
    print("Deleted Duplicates")
    print(f"Here is the New shape: {data.shape}")

Deleted Duplicates
Here is the New shape: (1033036, 8)

In [7]:
data.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [8]:
data.isnull().sum()

Invoice             0
StockCode           0
Description      4275
Quantity            0
InvoiceDate         0
Price               0
Customer ID    235151
Country             0
dtype: int64

In [9]:
data["Invoice"] = data["Invoice"].astype(str)

In [10]:
count_of_cancels = data["Invoice"].str.startswith("C").sum()
print("--"*50)
print(f"No Of Cancelled orders = {count_of_cancels}")
print("--"*50)

----------------------------------------------------------------------------------------------------
No Of Cancelled orders = 19104
----------------------------------------------------------------------------------------------------

In [11]:
data[data["Invoice"].str.startswith("C",na= True)].sample()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
622857,C544608,22973,CHILDREN'S CIRCUS PARADE MUG,-1,2011-02-22 10:00:00,1.65,15290.0,United Kingdom

In [12]:
data[data["Price"] == 0].sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
839103,564530,22683,FRENCH BLUE METAL DOOR SIGN 8,3,2011-08-25 14:57:00,0.0,NaN,United Kingdom
167838,505285,85221,?,-1120,2010-04-21 11:48:00,0.0,NaN,United Kingdom
256381,514133,21165,NaN,-155,2010-06-30 13:25:00,0.0,NaN,United Kingdom
629891,545176,22697,GREEN REGENCY TEACUP AND SAUCER,1,2011-02-28 14:19:00,0.0,NaN,United Kingdom
641272,546145,21537,?,-80,2011-03-09 16:39:00,0.0,NaN,United Kingdom

---
## Observation
- Dropped rows where **Price = 0** because they are **invalid transactions**
---

In [13]:
invalid_data = data[data["Price"] == 0]
data.drop(invalid_data.index,inplace=True)
print("--"*50)
print("Dropped unnecessary data")
print(f"shape of the data {data.shape}")
print("description nulls = ",data["Description"].isnull().sum())
print("--"*50)

----------------------------------------------------------------------------------------------------
Dropped unnecessary data
shape of the data (1027022, 8)
description nulls =  0
----------------------------------------------------------------------------------------------------

## Observation

- All rows with missing **Description** had **Price = 0**.
- Removing rows where **Price = 0** also removed all missing values in **Description**.

In [14]:
data[data["Price"] < 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

## Observation

- Negative **Price** is not a sale.
- It is a company adjustment.
- Removed these rows.

In [15]:
data.drop(data[data["Price"] < 0].index,inplace=True)

In [16]:
data[(data["Quantity"] < 0) & (~data["Invoice"].str.startswith("C", na=False))]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

## Observation

- There are no negative quantities except for cancelled orders.

In [17]:
print(data["Customer ID"].isnull().sum())

229202

In [18]:
data["Customer ID"] = data["Customer ID"].fillna("Unknown")

In [19]:
data.head(2)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom

In [20]:
data["sales"] = data["Quantity"] * data["Price"]

In [21]:
data.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
sales          0
dtype: int64

In [22]:
data.dtypes

Invoice                   str
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID            object
Country                   str
sales                 float64
dtype: object

In [23]:
data.to_excel(r"C:\Users\shiva\Downloads\Online_Retail_Cleaned.xlsx", index=False)
print("Data Saved Successfully")

Data Saved Successfully